spring:
  application:
    name: customer-service
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: POSTGRESQL

logging:
  config: classpath:configs/logback-spring.xml
  level:
    root: ERROR
  file:
    name: logs/dev-app.log

server:
  servlet:
    context-path: /api/v1/customers/
  port: 8081
